before:
  hooks:
    - go mod download
    - go mod verify

builds:
  - id: logryph
    main: ./main.go
    binary: logryph
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

  - id: logryph-cli
    main: ./cmd/logryph-cli/main.go
    binary: logryph-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - id: logryph
    builds:
      - logryph
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - logryph-policy.yaml

  - id: logryph-cli
    builds:
      - logryph-cli
    name_template: >-
      {{ .ProjectName }}-cli_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

sboms:
  - id: logryph-sbom
    artifacts: archive
    documents:
      - "${artifact}.sbom.spdx.json"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Security'
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## Logryph {{ .Tag }} Release
    
    Cryptographically auditable MCP proxy with tamper-evident ledger.
    
  footer: |
    ## Installation
    
    Download the appropriate archive for your platform, extract it, and add the binary to your PATH.
    
    ### Verify checksums
    ```bash
    sha256sum -c checksums.txt
    ```
